// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "test.mdx": () => import("../content/docs/test.mdx?collection=docs"), "glossary/aws-kendra.mdx": () => import("../content/docs/glossary/aws-kendra.mdx?collection=docs"), "glossary/aws-nova.mdx": () => import("../content/docs/glossary/aws-nova.mdx?collection=docs"), "glossary/cline.mdx": () => import("../content/docs/glossary/cline.mdx?collection=docs"), "glossary/deepgram.mdx": () => import("../content/docs/glossary/deepgram.mdx?collection=docs"), "glossary/ex-ai.mdx": () => import("../content/docs/glossary/ex-ai.mdx?collection=docs"), "glossary/firecrawl.mdx": () => import("../content/docs/glossary/firecrawl.mdx?collection=docs"), "glossary/gainsite.mdx": () => import("../content/docs/glossary/gainsite.mdx?collection=docs"), "glossary/github-codespaces.mdx": () => import("../content/docs/glossary/github-codespaces.mdx?collection=docs"), "glossary/google-a2ui.mdx": () => import("../content/docs/glossary/google-a2ui.mdx?collection=docs"), "glossary/hero-ui.mdx": () => import("../content/docs/glossary/hero-ui.mdx?collection=docs"), "glossary/index.mdx": () => import("../content/docs/glossary/index.mdx?collection=docs"), "glossary/mistral-ocr.mdx": () => import("../content/docs/glossary/mistral-ocr.mdx?collection=docs"), "glossary/openai-whisper.mdx": () => import("../content/docs/glossary/openai-whisper.mdx?collection=docs"), "glossary/raindrop.mdx": () => import("../content/docs/glossary/raindrop.mdx?collection=docs"), "glossary/zapier-developer-tools.mdx": () => import("../content/docs/glossary/zapier-developer-tools.mdx?collection=docs"), "projects/forms-workflow.mdx": () => import("../content/docs/projects/forms-workflow.mdx?collection=docs"), "projects/index.mdx": () => import("../content/docs/projects/index.mdx?collection=docs"), "projects/landing-page.mdx": () => import("../content/docs/projects/landing-page.mdx?collection=docs"), "projects/meeting-summary.mdx": () => import("../content/docs/projects/meeting-summary.mdx?collection=docs"), }),
};
export default browserCollections;